name: phBot plugin template
author: Mohamed Rabie Elmdary
nickname: ProfessionaL
email: engm5081@gmail.com
github: https://github.com/mohamedElmdary
telegram: https://t.me/MohamedElmdary
license: MIT
